services:
  - type: web
    name: data-viz-platform
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://raw.githack.com"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
    routes:
      - type: rewrite
        source: /*
        destination: /index.html