services:
  - type: web
    name: data-viz-platform
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'none'"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
    routes:
      - type: rewrite
        source: /*
        destination: /index.html